### PR TITLE
Add siwe auth migration

### PR DESCRIPTION
**Pull request by pconerly**
Add the migration for `siwe_auth`, and add back the migration for `examples/notepad`. Addresses https://github.com/payton/django-siwe-auth/issues/27 Mea culpa!

### CODE REVIEW

**Comment by payton** [comment]
@pconerly Now that I think about it, I wouldn't mind ignoring migration files for the example applications all together. It's already documented to run `makemigrations` for the demos, so this will be generated for the user.

As for `siwe_auth`, that should probably stay.

**Comment by pconerly** [comment]
Sounds good, I'll remove that `examples/notepad/app/migrations/0001_initial.py` from this branch and add a `.gitignore` rule

**Comment by pconerly** [comment]
@payton updated with changes

**Review by payton — APPROVED** [review]

**Comment by payton** [comment]
Incredible :pray:

**Pull request merged**
