### PR TITLE
Fixed db migration error

### PR DESCRIPTION
**Pull request by JasperAlexander**
Changed gitignore file to allow migrations folders, to avoid the need of running multiple makemigration commands. Fixes #49.

### CODE REVIEW

**Review by payton — CHANGES_REQUESTED** [review]
Thanks, @JasperAlexander! Can you please include the migration files for Notebook/SharedNotebook?

**Comment by JasperAlexander** [comment]
> Thanks, @JasperAlexander! Can you please include the migration files for Notebook/SharedNotebook?

Why would you include those?

**Comment by payton** [comment]
@JasperAlexander , actually I suppose it's not a big deal. We do for siwe_auth, but as an example app I suppose it's fine to re-run it each time. Thanks for fixing this!

**Review by payton — APPROVED** [review]

**Comment by payton** [comment]
@JasperAlexander you should be able to redeem a GitPOAP now for your commit! (if you're interested) See above for details.

**Comment by JasperAlexander** [comment]
> @JasperAlexander you should be able to redeem a GitPOAP now for your commit! (if you're interested) See above for details.

Thanks! I just redeemed the GitPOAP.

**Comment by pconerly** [comment]
Thanks for this @JasperAlexander !

**Pull request merged**
